drop table if exists category CASCADE;

drop table if exists inventory CASCADE; 

create table category (
   id integer generated by default as identity,
    name varchar(255) not null,
    parent_id integer,
    primary key (id)
);

create table inventory (
   id bigint generated by default as identity,
    name varchar(255) not null,
    quantity integer,
    belong_to integer not null,
    primary key (id)
);

alter table category 
   add constraint fk_parent_category 
   foreign key (parent_id) 
   references category;

alter table inventory 
   add constraint fk_inventory_category 
   foreign key (belong_to) 
   references category;
